// Generated by gencpp from file udpcom/udp2master.msg
// DO NOT EDIT!


#ifndef UDPCOM_MESSAGE_UDP2MASTER_H
#define UDPCOM_MESSAGE_UDP2MASTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace udpcom
{
template <class ContainerAllocator>
struct udp2master_
{
  typedef udp2master_<ContainerAllocator> Type;

  udp2master_()
    : yourcase(0)
    , yourballdt(0.0)  {
    }
  udp2master_(const ContainerAllocator& _alloc)
    : yourcase(0)
    , yourballdt(0.0)  {
  (void)_alloc;
    }



   typedef int32_t _yourcase_type;
  _yourcase_type yourcase;

   typedef double _yourballdt_type;
  _yourballdt_type yourballdt;





  typedef boost::shared_ptr< ::udpcom::udp2master_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::udpcom::udp2master_<ContainerAllocator> const> ConstPtr;

}; // struct udp2master_

typedef ::udpcom::udp2master_<std::allocator<void> > udp2master;

typedef boost::shared_ptr< ::udpcom::udp2master > udp2masterPtr;
typedef boost::shared_ptr< ::udpcom::udp2master const> udp2masterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::udpcom::udp2master_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::udpcom::udp2master_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace udpcom

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'udpcom': ['/home/robit/catkin_ws/src/udpcom/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::udpcom::udp2master_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::udpcom::udp2master_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::udpcom::udp2master_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::udpcom::udp2master_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::udpcom::udp2master_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::udpcom::udp2master_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::udpcom::udp2master_<ContainerAllocator> >
{
  static const char* value()
  {
    return "18f55e95f94ae45107e73ae92fd88961";
  }

  static const char* value(const ::udpcom::udp2master_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x18f55e95f94ae451ULL;
  static const uint64_t static_value2 = 0x07e73ae92fd88961ULL;
};

template<class ContainerAllocator>
struct DataType< ::udpcom::udp2master_<ContainerAllocator> >
{
  static const char* value()
  {
    return "udpcom/udp2master";
  }

  static const char* value(const ::udpcom::udp2master_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::udpcom::udp2master_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 yourcase\n\
float64 yourballdt\n\
";
  }

  static const char* value(const ::udpcom::udp2master_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::udpcom::udp2master_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.yourcase);
      stream.next(m.yourballdt);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct udp2master_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::udpcom::udp2master_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::udpcom::udp2master_<ContainerAllocator>& v)
  {
    s << indent << "yourcase: ";
    Printer<int32_t>::stream(s, indent + "  ", v.yourcase);
    s << indent << "yourballdt: ";
    Printer<double>::stream(s, indent + "  ", v.yourballdt);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UDPCOM_MESSAGE_UDP2MASTER_H
