// Generated by gencpp from file udpcom/udp_gamecase.msg
// DO NOT EDIT!


#ifndef UDPCOM_MESSAGE_UDP_GAMECASE_H
#define UDPCOM_MESSAGE_UDP_GAMECASE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace udpcom
{
template <class ContainerAllocator>
struct udp_gamecase_
{
  typedef udp_gamecase_<ContainerAllocator> Type;

  udp_gamecase_()
    : gamecase(0)  {
    }
  udp_gamecase_(const ContainerAllocator& _alloc)
    : gamecase(0)  {
  (void)_alloc;
    }



   typedef int32_t _gamecase_type;
  _gamecase_type gamecase;





  typedef boost::shared_ptr< ::udpcom::udp_gamecase_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::udpcom::udp_gamecase_<ContainerAllocator> const> ConstPtr;

}; // struct udp_gamecase_

typedef ::udpcom::udp_gamecase_<std::allocator<void> > udp_gamecase;

typedef boost::shared_ptr< ::udpcom::udp_gamecase > udp_gamecasePtr;
typedef boost::shared_ptr< ::udpcom::udp_gamecase const> udp_gamecaseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::udpcom::udp_gamecase_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::udpcom::udp_gamecase_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace udpcom

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'udpcom': ['/home/robit/catkin_ws/src/udpcom/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::udpcom::udp_gamecase_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::udpcom::udp_gamecase_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::udpcom::udp_gamecase_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::udpcom::udp_gamecase_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::udpcom::udp_gamecase_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::udpcom::udp_gamecase_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::udpcom::udp_gamecase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f27803a7c3da9034084289e40e20883";
  }

  static const char* value(const ::udpcom::udp_gamecase_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f27803a7c3da903ULL;
  static const uint64_t static_value2 = 0x4084289e40e20883ULL;
};

template<class ContainerAllocator>
struct DataType< ::udpcom::udp_gamecase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "udpcom/udp_gamecase";
  }

  static const char* value(const ::udpcom::udp_gamecase_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::udpcom::udp_gamecase_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 gamecase\n\
";
  }

  static const char* value(const ::udpcom::udp_gamecase_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::udpcom::udp_gamecase_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.gamecase);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct udp_gamecase_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::udpcom::udp_gamecase_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::udpcom::udp_gamecase_<ContainerAllocator>& v)
  {
    s << indent << "gamecase: ";
    Printer<int32_t>::stream(s, indent + "  ", v.gamecase);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UDPCOM_MESSAGE_UDP_GAMECASE_H
